### PR TITLE
Fixed issue 35

### PR DESCRIPTION
**Pull request by fk00750**
Making use of sharer.js #35 

## 👨‍💻 Changes proposed

- [x] Add sharer.js
- [x] functionality to share the page on social media.
- [ ] functionality to share Qrcode.

## Note 
- Right now the share buttons for various social media platforms only share the link of the whole webpage.
- For future reference, sharing of Qrcode generated by the application can be added.

### CODE REVIEW

**Comment by bacloud22** [comment]
@fk00750 I got it, but this a great addition already!! Thank you so much 😀

**Review by bacloud22 — COMMENTED** [review]
Hey great addition! 
Please let me know if you could use the same indentation and code style? 
Otherwise it's fine gonna merge anyway

**Comment by bacloud22** [comment]
Hey what's up with html.html 🙄😁

**Comment by fk00750** [comment]
@oh sorry I have forgotten to remove it ... Wait, i will fix it 😅

**Comment by bacloud22** [comment]
Great addition

**Comment by bacloud22** [comment]
Hey @fk00750 
Could you please rather rely on the minified sharer.js file? Alone, rather than the node_midules package. 
I guess that not a good way to serve node_modules folder in such a static js app. 

Some would you that but then build some target files alone. But never the whole node_modules.to be server for the web browsers. 
Could you revert that please

**Comment by bacloud22** [comment]
Just put that sharer.min.js in here 
https://github.com/bacloud22/so-cards/tree/main/src

**Comment by fk00750** [comment]
Ohk i am making the changes

**Comment by bacloud22** [comment]
@fk00750 still in progress ? willing to work on it or I assign it to myself ?

**Comment by fk00750** [comment]
@bacloud22 i will work on it ... Now i am trying to make it pwa

**Pull request merged**
